# Generated by Django 2.0.1 on 2018-03-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(max_length=50)),
                ('picture', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
