# Generated by Django 2.0.1 on 2018-03-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='picture',
            field=models.FileField(upload_to='images/'),
        ),
    ]
