# Generated by Django 2.0.1 on 2018-03-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopping_cart', '0003_auto_20180322_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
