# Generated by Django 2.0.1 on 2018-03-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopping_cart', '0004_auto_20180323_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
