# Generated by Django 2.0.1 on 2018-03-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopping_cart', '0006_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
