# Generated by Django 2.0.1 on 2018-03-31 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_shopping_cart', '0008_auto_20180331_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='user_name',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
