# Generated by Django 2.0.1 on 2018-03-31 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopping_cart', '0009_auto_20180331_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_id', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField(default=0)),
                ('payment', models.CharField(max_length=10)),
                ('product_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='online_shopping_cart.Items')),
            ],
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='email',
        ),
    ]
