# Generated by Django 2.0.1 on 2018-03-31 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_shopping_cart', '0010_auto_20180331_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_id', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
                ('username', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='voucher',
            name='v_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='online_shopping_cart.ShippingInfo'),
        ),
    ]
