# Generated by Django 2.0.1 on 2018-03-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopping_cart', '0011_auto_20180331_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
