# Generated by Django 2.0.1 on 2018-03-31 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopping_cart', '0013_auto_20180331_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='payment',
        ),
    ]
