# Generated by Django 2.0.1 on 2018-03-31 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopping_cart', '0014_remove_voucher_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippinginfo',
            name='v_id',
        ),
    ]
