# Generated by Django 2.0.1 on 2018-04-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopping_cart', '0016_shippinginfo_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginfo',
            name='payment_status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
